### ISSUE TITLE
aplication example and documentation started point?

### ISSUE THREAD

**Issue by mckaygerhard** [HijenHEK/laravel-backend-template#10]
aplication example and documentation started point?

i mean.. some people just want quick start event try to guess all the implementations and usage, you already know how to use it but others must have more time to assimilate it @HijenHEK

**Comment by HijenHEK** [comment]
@mckaygerhard 

everything is available in the readme

- whats included in terms of functionalities
- how to install it locally or using docker
- how to run tests
- how to open api documentation

if there is anything else you think might add up to this feel free to create a pull request.

**Comment by mckaygerhard** [comment]
i was to try being polite but your readme is crap.. only describe full technicall aspects but does not describe steps for novice laravel implementations.. 

also the routing is a mess without explanation cos is clear more advanced rather than the documentation said.. @HijenHEK 

no surprised why this is not so used ..

**Comment by HijenHEK** [comment]
@mckaygerhard ,

you failed to understand the readme, you failed to be polite and you failed to understand the concept of GitHub because i don't work here !

**So childish of you to say "no surprised why it is not used" for a repo that has 7 stars.**. this repo helped me personally and i still use it to this day also this repo is now used in 3 production software one of them in my current company I wouldn't call that a failure.

have some courtesy and learn how to talk to people.
